name: Ansible
on:
  workflow_dispatch:
  push:
    paths:
      - 'ansible/**'
      - '.github/workflows/ansible_flow.yml'

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_REMOTE_USER: ubuntu

          
