name: Deploy FastAPI with Ansible

on:
  workflow_dispatch:  
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ansible  

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Write SSH key
      run: |
        echo "${{ secrets.EC2_PRV_KEY }}" > ansible_key
        chmod 600 ansible_key

    # - name: Create Ansible inventory
    #   run: |
    #     echo "[web_servers]" > inventory
    #     echo "${{ secrets.ANSIBLE_HOST }} ansible_user=ubuntu ansible_ssh_private_key_file=./ansible_key" >> inventory
    - name: Add EC2 to known_hosts
      run: |
        echo "${{ secrets.KNOWN_HOST_ENTRY }}" > ~/.ssh/known_hosts

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory playbook.yml
      # env:
      #   ANSIBLE_HOST_KEY_CHECKING: "False"
