name: Terraform

on:
  workflow_dispatch: 
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform_flow.yml'
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terrraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply tfplan.binary
        working-directory: ./terraform

        

        
      
